# Port
spring.application.name=Backend
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/glowmart
spring.datasource.username=root
spring.datasource.password=6723

jwt.secret=${JWT_SECRET:SGVsbG8gV29ybGQgVGhpcyBpcyBhIHZlcnkgbG9uZyBhbmQgc2VjdXJlIEpXVCBzZWNyZXQga2V5IHRoYXQgaGFzIG1vcmUgdGhhbiA1MTIgYml0cyB3aGVuIGRlY29kZWQgd2l0aCBCYXNlNjQgZW5jb2Rpbmc=}
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=false

# OTP Configuration
app.otp.expiry-minutes=5
app.otp.max-attempts=3

# Logging level for BusinessException
logging.level.com.example.backend.exception=DEBUG

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aranoz.contact@gmail.com
spring.mail.from-name=Glow Mart
spring.mail.password=zfskrvcpptajrcva
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# App Configuration
app.email.from-name=aranoz.contact@gmail.com
app.base-url=http://localhost:3000

# Mock email for development (true = không gửi thật, false = gửi thật)
app.email.mock=false